CREATE TABLE IF NOT EXISTS game (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    width INTEGER,
    height INTEGER,
    board TEXT,
    player1 INTEGER,
    player2 INTEGER,
    turn INTEGER
);

CREATE TABLE IF NOT EXISTS player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    win INTEGER
);
